<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="snippset">
  <!--============= MACROS =============-->
  <xacro:macro name="default_base" params="x y z">
    <visual>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </visual>
    <collision>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="default_cylinder" params="length radius color mass x y z">
    <visual>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length}" radius="${radius}"/>
      </geometry>
      <material name="${color}"/>
    </visual>
    <collision>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length/1.05}" radius="${radius/1.05}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass*(length**2+3*radius**2)/12}"
               ixy="0" iyy="${mass*(length**2+3*radius**2)/12}"
               ixz="0" iyz="0" izz="${mass*radius**2/2}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="default_box" params="length width height color mass">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="${color}"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length/1.05} ${width/1.05} ${height/1.05}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass*(height**2)*(width**2)/12}"
               ixy="0" iyy="${mass*(length**2)*(height**2)/12}"
               ixz="0" iyz="0" izz="${mass*(length**2)*(width**2)/12}"/>
    </inertial>
  </xacro:macro>

<!--============= SENSORS =============-->
  <xacro:macro name="lidar_sensor">
    <sensor type="ray" name="lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.0472</min_angle>
            <max_angle>1.0472</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>15.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="laser" filename="libRayPlugin.so">
        <topicName>/round_object/laser/scan</topicName>
        <frameName>sensor_link</frameName>
      </plugin>
      <plugin name="ros_laser" filename="libgazebo_ros_laser.so">
        <topicName>/round_object/laser/scan</topicName>
        <frameName>sensor_link</frameName>
      </plugin>
    </sensor>
  </xacro:macro>

  <xacro:macro name="imu">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>50.0</update_rate>
      <visualize>true</visualize>
      <topic>__default_topic__</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>imu</topicName>
        <bodyName>sensor_link</bodyName>
        <updateRateHZ>10.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>sensor_link</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </xacro:macro>
</robot>
